In [3]:
import numpy as np
x = np.array([[8,6,3],[2,3,4],[0,0,0]])
y = np.array([[2,5,1],[2,3,4],[5,2,1]])
x + y

array([[10, 11,  4],
       [ 4,  6,  8],
       [ 5,  2,  1]])

In [4]:
c=x.dot(y)
print(c)

[[43 64 35]
 [30 27 18]
 [ 0  0  0]]


In [8]:
x / y

array([[4. , 1.2, 3. ],
       [1. , 1. , 1. ],
       [0. , 0. , 0. ]])

In [9]:
x % y

array([[0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)